// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pilot_local.proto
// Protobuf C++ Version: 5.29.3

#include "pilot_local.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace unifly {
namespace schema {
              template <typename>
PROTOBUF_CONSTEXPR ReadLocalInfrequent::ReadLocalInfrequent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct ReadLocalInfrequentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadLocalInfrequentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadLocalInfrequentDefaultTypeInternal() {}
  union {
    ReadLocalInfrequent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadLocalInfrequentDefaultTypeInternal _ReadLocalInfrequent_default_instance_;

inline constexpr ReadLocalFrequent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : lat_{0},
        lon_{0},
        pitch_{0},
        bank_{0},
        heading_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReadLocalFrequent::ReadLocalFrequent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReadLocalFrequentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadLocalFrequentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadLocalFrequentDefaultTypeInternal() {}
  union {
    ReadLocalFrequent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadLocalFrequentDefaultTypeInternal _ReadLocalFrequent_default_instance_;
}  // namespace schema
}  // namespace unifly
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_pilot_5flocal_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_pilot_5flocal_2eproto = nullptr;
const ::uint32_t
    TableStruct_pilot_5flocal_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::unifly::schema::ReadLocalFrequent, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::unifly::schema::ReadLocalFrequent, _impl_.lat_),
        PROTOBUF_FIELD_OFFSET(::unifly::schema::ReadLocalFrequent, _impl_.lon_),
        PROTOBUF_FIELD_OFFSET(::unifly::schema::ReadLocalFrequent, _impl_.pitch_),
        PROTOBUF_FIELD_OFFSET(::unifly::schema::ReadLocalFrequent, _impl_.bank_),
        PROTOBUF_FIELD_OFFSET(::unifly::schema::ReadLocalFrequent, _impl_.heading_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::unifly::schema::ReadLocalInfrequent, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::unifly::schema::ReadLocalFrequent)},
        {13, -1, -1, sizeof(::unifly::schema::ReadLocalInfrequent)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::unifly::schema::_ReadLocalFrequent_default_instance_._instance,
    &::unifly::schema::_ReadLocalInfrequent_default_instance_._instance,
};
const char descriptor_table_protodef_pilot_5flocal_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021pilot_local.proto\022\runifly.schema\"[\n\021Re"
    "adLocalFrequent\022\013\n\003lat\030\001 \001(\001\022\013\n\003lon\030\002 \001("
    "\001\022\r\n\005pitch\030\003 \001(\001\022\014\n\004bank\030\004 \001(\001\022\017\n\007headin"
    "g\030\005 \001(\001\"\025\n\023ReadLocalInfrequentb\006proto3"
};
static ::absl::once_flag descriptor_table_pilot_5flocal_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_pilot_5flocal_2eproto = {
    false,
    false,
    158,
    descriptor_table_protodef_pilot_5flocal_2eproto,
    "pilot_local.proto",
    &descriptor_table_pilot_5flocal_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_pilot_5flocal_2eproto::offsets,
    file_level_enum_descriptors_pilot_5flocal_2eproto,
    file_level_service_descriptors_pilot_5flocal_2eproto,
};
namespace unifly {
namespace schema {
// ===================================================================

class ReadLocalFrequent::_Internal {
 public:
};

ReadLocalFrequent::ReadLocalFrequent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:unifly.schema.ReadLocalFrequent)
}
ReadLocalFrequent::ReadLocalFrequent(
    ::google::protobuf::Arena* arena, const ReadLocalFrequent& from)
    : ReadLocalFrequent(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ReadLocalFrequent::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ReadLocalFrequent::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, lat_),
           0,
           offsetof(Impl_, heading_) -
               offsetof(Impl_, lat_) +
               sizeof(Impl_::heading_));
}
ReadLocalFrequent::~ReadLocalFrequent() {
  // @@protoc_insertion_point(destructor:unifly.schema.ReadLocalFrequent)
  SharedDtor(*this);
}
inline void ReadLocalFrequent::SharedDtor(MessageLite& self) {
  ReadLocalFrequent& this_ = static_cast<ReadLocalFrequent&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ReadLocalFrequent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReadLocalFrequent(arena);
}
constexpr auto ReadLocalFrequent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReadLocalFrequent),
                                            alignof(ReadLocalFrequent));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReadLocalFrequent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReadLocalFrequent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReadLocalFrequent::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReadLocalFrequent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReadLocalFrequent::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReadLocalFrequent>(), &ReadLocalFrequent::ByteSizeLong,
            &ReadLocalFrequent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_._cached_size_),
        false,
    },
    &ReadLocalFrequent::kDescriptorMethods,
    &descriptor_table_pilot_5flocal_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReadLocalFrequent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2> ReadLocalFrequent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::unifly::schema::ReadLocalFrequent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double lat = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.lat_)}},
    // double lon = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.lon_)}},
    // double pitch = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.pitch_)}},
    // double bank = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.bank_)}},
    // double heading = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 63, 0, PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.heading_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // double lat = 1;
    {PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.lat_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double lon = 2;
    {PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.lon_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double pitch = 3;
    {PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.pitch_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double bank = 4;
    {PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.bank_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double heading = 5;
    {PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.heading_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ReadLocalFrequent::Clear() {
// @@protoc_insertion_point(message_clear_start:unifly.schema.ReadLocalFrequent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.lat_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.heading_) -
      reinterpret_cast<char*>(&_impl_.lat_)) + sizeof(_impl_.heading_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReadLocalFrequent::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReadLocalFrequent& this_ = static_cast<const ReadLocalFrequent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReadLocalFrequent::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReadLocalFrequent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:unifly.schema.ReadLocalFrequent)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double lat = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_lat()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_lat(), target);
          }

          // double lon = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_lon()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_lon(), target);
          }

          // double pitch = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_pitch()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_pitch(), target);
          }

          // double bank = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_bank()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_bank(), target);
          }

          // double heading = 5;
          if (::absl::bit_cast<::uint64_t>(this_._internal_heading()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                5, this_._internal_heading(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:unifly.schema.ReadLocalFrequent)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReadLocalFrequent::ByteSizeLong(const MessageLite& base) {
          const ReadLocalFrequent& this_ = static_cast<const ReadLocalFrequent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReadLocalFrequent::ByteSizeLong() const {
          const ReadLocalFrequent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:unifly.schema.ReadLocalFrequent)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double lat = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_lat()) != 0) {
              total_size += 9;
            }
            // double lon = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_lon()) != 0) {
              total_size += 9;
            }
            // double pitch = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_pitch()) != 0) {
              total_size += 9;
            }
            // double bank = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_bank()) != 0) {
              total_size += 9;
            }
            // double heading = 5;
            if (::absl::bit_cast<::uint64_t>(this_._internal_heading()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReadLocalFrequent::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReadLocalFrequent*>(&to_msg);
  auto& from = static_cast<const ReadLocalFrequent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:unifly.schema.ReadLocalFrequent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_lat()) != 0) {
    _this->_impl_.lat_ = from._impl_.lat_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_lon()) != 0) {
    _this->_impl_.lon_ = from._impl_.lon_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_pitch()) != 0) {
    _this->_impl_.pitch_ = from._impl_.pitch_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_bank()) != 0) {
    _this->_impl_.bank_ = from._impl_.bank_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_heading()) != 0) {
    _this->_impl_.heading_ = from._impl_.heading_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReadLocalFrequent::CopyFrom(const ReadLocalFrequent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:unifly.schema.ReadLocalFrequent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReadLocalFrequent::InternalSwap(ReadLocalFrequent* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.heading_)
      + sizeof(ReadLocalFrequent::_impl_.heading_)
      - PROTOBUF_FIELD_OFFSET(ReadLocalFrequent, _impl_.lat_)>(
          reinterpret_cast<char*>(&_impl_.lat_),
          reinterpret_cast<char*>(&other->_impl_.lat_));
}

::google::protobuf::Metadata ReadLocalFrequent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReadLocalInfrequent::_Internal {
 public:
};

ReadLocalInfrequent::ReadLocalInfrequent(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:unifly.schema.ReadLocalInfrequent)
}
ReadLocalInfrequent::ReadLocalInfrequent(
    ::google::protobuf::Arena* arena,
    const ReadLocalInfrequent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReadLocalInfrequent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:unifly.schema.ReadLocalInfrequent)
}

inline void* ReadLocalInfrequent::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReadLocalInfrequent(arena);
}
constexpr auto ReadLocalInfrequent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReadLocalInfrequent),
                                            alignof(ReadLocalInfrequent));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReadLocalInfrequent::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReadLocalInfrequent_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReadLocalInfrequent::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<ReadLocalInfrequent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReadLocalInfrequent::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<ReadLocalInfrequent>(), &ReadLocalInfrequent::ByteSizeLong,
            &ReadLocalInfrequent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReadLocalInfrequent, _impl_._cached_size_),
        false,
    },
    &ReadLocalInfrequent::kDescriptorMethods,
    &descriptor_table_pilot_5flocal_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReadLocalInfrequent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> ReadLocalInfrequent::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::unifly::schema::ReadLocalInfrequent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata ReadLocalInfrequent::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace schema
}  // namespace unifly
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_pilot_5flocal_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
