// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pilot_remote.proto
// Protobuf C++ Version: 5.29.3

#ifndef pilot_5fremote_2eproto_2epb_2eh
#define pilot_5fremote_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_pilot_5fremote_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_pilot_5fremote_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_pilot_5fremote_2eproto;
namespace unifly {
namespace schema {
class WriteRemoteFrequent;
struct WriteRemoteFrequentDefaultTypeInternal;
extern WriteRemoteFrequentDefaultTypeInternal _WriteRemoteFrequent_default_instance_;
class WriteRemoteInfrequent;
struct WriteRemoteInfrequentDefaultTypeInternal;
extern WriteRemoteInfrequentDefaultTypeInternal _WriteRemoteInfrequent_default_instance_;
}  // namespace schema
}  // namespace unifly
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace unifly {
namespace schema {

// ===================================================================


// -------------------------------------------------------------------

class WriteRemoteInfrequent final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:unifly.schema.WriteRemoteInfrequent) */ {
 public:
  inline WriteRemoteInfrequent() : WriteRemoteInfrequent(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WriteRemoteInfrequent* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WriteRemoteInfrequent));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WriteRemoteInfrequent(
      ::google::protobuf::internal::ConstantInitialized);

  inline WriteRemoteInfrequent(const WriteRemoteInfrequent& from) : WriteRemoteInfrequent(nullptr, from) {}
  inline WriteRemoteInfrequent(WriteRemoteInfrequent&& from) noexcept
      : WriteRemoteInfrequent(nullptr, std::move(from)) {}
  inline WriteRemoteInfrequent& operator=(const WriteRemoteInfrequent& from) {
    CopyFrom(from);
    return *this;
  }
  inline WriteRemoteInfrequent& operator=(WriteRemoteInfrequent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WriteRemoteInfrequent& default_instance() {
    return *internal_default_instance();
  }
  static inline const WriteRemoteInfrequent* internal_default_instance() {
    return reinterpret_cast<const WriteRemoteInfrequent*>(
        &_WriteRemoteInfrequent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(WriteRemoteInfrequent& a, WriteRemoteInfrequent& b) { a.Swap(&b); }
  inline void Swap(WriteRemoteInfrequent* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WriteRemoteInfrequent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WriteRemoteInfrequent* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<WriteRemoteInfrequent>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const WriteRemoteInfrequent& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const WriteRemoteInfrequent& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "unifly.schema.WriteRemoteInfrequent"; }

 protected:
  explicit WriteRemoteInfrequent(::google::protobuf::Arena* arena);
  WriteRemoteInfrequent(::google::protobuf::Arena* arena, const WriteRemoteInfrequent& from);
  WriteRemoteInfrequent(::google::protobuf::Arena* arena, WriteRemoteInfrequent&& from) noexcept
      : WriteRemoteInfrequent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:unifly.schema.WriteRemoteInfrequent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const WriteRemoteInfrequent& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_pilot_5fremote_2eproto;
};
// -------------------------------------------------------------------

class WriteRemoteFrequent final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:unifly.schema.WriteRemoteFrequent) */ {
 public:
  inline WriteRemoteFrequent() : WriteRemoteFrequent(nullptr) {}
  ~WriteRemoteFrequent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WriteRemoteFrequent* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WriteRemoteFrequent));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WriteRemoteFrequent(
      ::google::protobuf::internal::ConstantInitialized);

  inline WriteRemoteFrequent(const WriteRemoteFrequent& from) : WriteRemoteFrequent(nullptr, from) {}
  inline WriteRemoteFrequent(WriteRemoteFrequent&& from) noexcept
      : WriteRemoteFrequent(nullptr, std::move(from)) {}
  inline WriteRemoteFrequent& operator=(const WriteRemoteFrequent& from) {
    CopyFrom(from);
    return *this;
  }
  inline WriteRemoteFrequent& operator=(WriteRemoteFrequent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WriteRemoteFrequent& default_instance() {
    return *internal_default_instance();
  }
  static inline const WriteRemoteFrequent* internal_default_instance() {
    return reinterpret_cast<const WriteRemoteFrequent*>(
        &_WriteRemoteFrequent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WriteRemoteFrequent& a, WriteRemoteFrequent& b) { a.Swap(&b); }
  inline void Swap(WriteRemoteFrequent* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WriteRemoteFrequent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WriteRemoteFrequent* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WriteRemoteFrequent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WriteRemoteFrequent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WriteRemoteFrequent& from) { WriteRemoteFrequent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WriteRemoteFrequent* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "unifly.schema.WriteRemoteFrequent"; }

 protected:
  explicit WriteRemoteFrequent(::google::protobuf::Arena* arena);
  WriteRemoteFrequent(::google::protobuf::Arena* arena, const WriteRemoteFrequent& from);
  WriteRemoteFrequent(::google::protobuf::Arena* arena, WriteRemoteFrequent&& from) noexcept
      : WriteRemoteFrequent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLatFieldNumber = 1,
    kLonFieldNumber = 2,
    kPitchFieldNumber = 3,
    kBankFieldNumber = 4,
    kHeadingFieldNumber = 5,
  };
  // double lat = 1;
  void clear_lat() ;
  double lat() const;
  void set_lat(double value);

  private:
  double _internal_lat() const;
  void _internal_set_lat(double value);

  public:
  // double lon = 2;
  void clear_lon() ;
  double lon() const;
  void set_lon(double value);

  private:
  double _internal_lon() const;
  void _internal_set_lon(double value);

  public:
  // double pitch = 3;
  void clear_pitch() ;
  double pitch() const;
  void set_pitch(double value);

  private:
  double _internal_pitch() const;
  void _internal_set_pitch(double value);

  public:
  // double bank = 4;
  void clear_bank() ;
  double bank() const;
  void set_bank(double value);

  private:
  double _internal_bank() const;
  void _internal_set_bank(double value);

  public:
  // double heading = 5;
  void clear_heading() ;
  double heading() const;
  void set_heading(double value);

  private:
  double _internal_heading() const;
  void _internal_set_heading(double value);

  public:
  // @@protoc_insertion_point(class_scope:unifly.schema.WriteRemoteFrequent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const WriteRemoteFrequent& from_msg);
    double lat_;
    double lon_;
    double pitch_;
    double bank_;
    double heading_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pilot_5fremote_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WriteRemoteFrequent

// double lat = 1;
inline void WriteRemoteFrequent::clear_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = 0;
}
inline double WriteRemoteFrequent::lat() const {
  // @@protoc_insertion_point(field_get:unifly.schema.WriteRemoteFrequent.lat)
  return _internal_lat();
}
inline void WriteRemoteFrequent::set_lat(double value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:unifly.schema.WriteRemoteFrequent.lat)
}
inline double WriteRemoteFrequent::_internal_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lat_;
}
inline void WriteRemoteFrequent::_internal_set_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lat_ = value;
}

// double lon = 2;
inline void WriteRemoteFrequent::clear_lon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = 0;
}
inline double WriteRemoteFrequent::lon() const {
  // @@protoc_insertion_point(field_get:unifly.schema.WriteRemoteFrequent.lon)
  return _internal_lon();
}
inline void WriteRemoteFrequent::set_lon(double value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:unifly.schema.WriteRemoteFrequent.lon)
}
inline double WriteRemoteFrequent::_internal_lon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lon_;
}
inline void WriteRemoteFrequent::_internal_set_lon(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lon_ = value;
}

// double pitch = 3;
inline void WriteRemoteFrequent::clear_pitch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pitch_ = 0;
}
inline double WriteRemoteFrequent::pitch() const {
  // @@protoc_insertion_point(field_get:unifly.schema.WriteRemoteFrequent.pitch)
  return _internal_pitch();
}
inline void WriteRemoteFrequent::set_pitch(double value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:unifly.schema.WriteRemoteFrequent.pitch)
}
inline double WriteRemoteFrequent::_internal_pitch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pitch_;
}
inline void WriteRemoteFrequent::_internal_set_pitch(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pitch_ = value;
}

// double bank = 4;
inline void WriteRemoteFrequent::clear_bank() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bank_ = 0;
}
inline double WriteRemoteFrequent::bank() const {
  // @@protoc_insertion_point(field_get:unifly.schema.WriteRemoteFrequent.bank)
  return _internal_bank();
}
inline void WriteRemoteFrequent::set_bank(double value) {
  _internal_set_bank(value);
  // @@protoc_insertion_point(field_set:unifly.schema.WriteRemoteFrequent.bank)
}
inline double WriteRemoteFrequent::_internal_bank() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bank_;
}
inline void WriteRemoteFrequent::_internal_set_bank(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bank_ = value;
}

// double heading = 5;
inline void WriteRemoteFrequent::clear_heading() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heading_ = 0;
}
inline double WriteRemoteFrequent::heading() const {
  // @@protoc_insertion_point(field_get:unifly.schema.WriteRemoteFrequent.heading)
  return _internal_heading();
}
inline void WriteRemoteFrequent::set_heading(double value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:unifly.schema.WriteRemoteFrequent.heading)
}
inline double WriteRemoteFrequent::_internal_heading() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heading_;
}
inline void WriteRemoteFrequent::_internal_set_heading(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heading_ = value;
}

// -------------------------------------------------------------------

// WriteRemoteInfrequent

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace schema
}  // namespace unifly


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // pilot_5fremote_2eproto_2epb_2eh
