name: "Build UniFly for macOS"

on:
  workflow_call:
  workflow_dispatch:

env:
  MIN_OS_VERSION: 11.0
  BUILD_TYPE: Release
  PLUGIN_DIR: ${{ github.workspace }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      ### Buid Plugin ###

      - name: Build
        run: |
          mkdir build
          cmake -B build -S . -DCMAKE_OSX_ARCHITECTURES x86_64;arm64 && cmake --build build

      # - name: Build plugin
      #   working-directory: ${{ env.PLUGIN_DIR }}
      #   run: |
      #     mkdir build && cd build
      #     cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.MIN_OS_VERSION }} && cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Extract debug symbols
        working-directory: ${{ github.workspace }}/build/
        run: |
          dsymutil UniFly-XPLM.xpl -o UniFly-XPLM.dSYM

      - name: Package plugin
        run: |
          mkdir -p ${{ github.workspace }}/UniFly/mac_x64
          cp ${{ github.workspace }}/build/mac_x64/UniFly-XPLM.xpl ${{ github.workspace }}/UniFly/mac_x64
          cp -R ${{ github.workspace }}/build/mac_x64/UniFly-XPLM.dSYM ${{ github.workspace }}/UniFly/mac_x64
          cp ${{ github.workspace }}/3rdparty/fmod/libfmod.dylib ${{ github.workspace }}/UniFly/mac_x64
          cp -R ${{ github.workspace }}/Resources ${{ github.workspace }}/UniFly/

      # - name: Fix FMOD rpath
      #   working-directory: ${{ github.workspace }}/UniFly/mac_x64
      #   run: |
      #     install_name_tool -id @executable_path/../../../Resources/plugins/xPilot/mac_x64/libfmod.dylib libfmod.dylib
      #     install_name_tool -change @rpath/libfmod.dylib @executable_path/../../../Resources/plugins/xPilot/mac_x64/libfmod.dylib xPilot.xpl
