name: "Build UniFly for Windows"

on:
  workflow_call:
  workflow_dispatch:

env:
  PLUGIN_DIR: ${{ github.workspace }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/checkout@master
        with:
          repository: protocolbuffers/protobuf
          path: "protobuf"

      ### Buid Protocol buffers with cmake ###

      - name: Build protocolbuffers
        run: |
          cd protobuf
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          ctest --test-dir build --verbose
          cmake --install build

      ### Buid Plugin ###

      - name: Build plugin
        run: |
          mkdir build
          cmake -B build -S . && cmake --build build


      - name: Package plugin
        run: |
          mkdir -p ${{ github.workspace }}/UniFly/win_x64
          cp ${{ github.workspace }}/build/UniFly-XPLM.xpl ${{ github.workspace }}/UniFly/win_x64
          cp ${{ github.workspace }}/build/UniFly-XPLM.pdb ${{ github.workspace }}/UniFly/win_x64
          cp ${{ github.workspace }}/3rdparty/fmod/fmod.dll ${{ github.workspace }}/UniFly/win_x64
          cp -R ${{ github.workspace }}/Resources ${{ github.workspace }}/UniFly/
